/*
 * Braden Rosengren
 * Progress through Project Euler
 * 2018
 */
package Problems1_25;

/**
 *
 * @author br16643
 */
public class Problem2 {

	/**
	 *
	 *
	 * Each new term in the Fibonacci sequence is generated by adding the
	 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
	 *
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 *
	 * By considering the terms in the Fibonacci sequence whose values do not
	 * exceed four million, find the sum of the even-valued terms.
	 *
	 * @param args
	 */
	public static void main(String[] args) {
		int num = 1;
		int tmp;
		int prev = 0;
		int result = 0;
		while (num < 4000000) {
			tmp = num;
			num += prev;
			if (num > 4000000) {
				continue;
			}
			prev = tmp;
			System.out.println(num);
			if ((num % 2) == 0) {
				result += num;
			}
		}

		System.out.println("\n" + result);
	}
}
